### ISSUE TITLE
TypeError: Cannot read property 'databaseURL' of undefined

### ISSUE THREAD

**Issue by troixanhvuctham** [googlecodelabs/smarthome-washer#12]
I follow the instruction on https://codelabs.developers.google.com/codelabs/smarthome-washer/index.html#2. But when I run 'firebase deploy', it show the error: 
Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'databaseURL' of undefined
    at RepoManager.databaseFromApp (C:\Users\ERCLab\Desktop\smarthome-washer\washer-start\functions\node_modules\@firebase\database\dist\index.node.cjs.js:14985:39)
    at Object.instance.INTERNAL.registerService.Reference [as database] (C:\Users\ERCLab\Desktop\smarthome-washer\washer-start\functions\node_modules\@firebase\database\dist\index.node.cjs.js:15526:130)
    at FirebaseAppImpl._getService (C:\Users\ERCLab\Desktop\smarthome-washer\washer-start\functions\node_modules\@firebase\app\dist\index.cjs.js:134:66)
    at FirebaseAppImpl.(anonymous function) [as database] (C:\Users\ERCLab\Desktop\smarthome-washer\washer-start\functions\node_modules\@firebase\app\dist\index.cjs.js:323:31)
    at Object.serviceNamespace [as database] (C:\Users\ERCLab\Desktop\smarthome-washer\washer-start\functions\node_modules\@firebase\app\dist\index.cjs.js:308:32)
    at Object.<anonymous> (C:\Users\ERCLab\Desktop\smarthome-washer\washer-start\functions\index.js:26:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

I don't know how to fix it

**Comment by papazzzoglo** [comment]
I have a same error too

**Comment by Fleker** [comment]
This is like #10.

Update the snippet as:

```
const firebase = require('firebase');
const admin = require('firebase-admin');
// Initialize Firebase
firebase.initializeApp(JSON.parse(process.env.FIREBASE_CONFIG));
```

**Comment by troixanhvuctham** [comment]
It help, thank you, @Fleker

**Comment by cars10w** [comment]
Yup, that snippet helped me as well.  Just in time for the event next week. :-)

**Comment by Fleker** [comment]
The code has been updated with the fix.

**Comment by 2022karanbhasin** [comment]
What if we don't have a process.env file?
