### ISSUE TITLE
Typo in Washer onSync response

### ISSUE THREAD

**Issue by Fleker** [googlecodelabs/smarthome-washer#6]
```
Error occurred while parsing your function triggers.

/home/fleker/voice-tech-to/smarthome-washer/washer-start/functions/index.js:83
          defaultNames: 'My Washer'],
                                   ^

SyntaxError: Unexpected token ]
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /usr/lib/node_modules/firebase-tools/lib/triggerParser.js:21:11
```

**Comment by Fleker** [comment]
Fixed
