### ISSUE TITLE
deploy fails in Step #3

### ISSUE THREAD

**Issue by prafullkotecha** [googlecodelabs/smarthome-washer#9]
First error:
```
Error: package.json in functions directory has an engines field which is unsupported. The only valid choices are: {"node": "8"} and {"node": "6"}.
```

After I change the package.json file to use "node":"8", then I get following error:

```
i  functions: preparing functions directory for uploading...

Error: Error occurred while parsing your function triggers.

TypeError: Cannot read property 'databaseURL' of undefined
    at RepoManager.databaseFromApp (/Users/prafulll/code/personal/direkshanProjects/googleAssistant/smarthome-washer/washer-start/functions/node_modules/@firebase/database/dist/index.node.cjs.js:14985:39)
    at Object.instance.INTERNAL.registerService.Reference [as database] (/Users/prafulll/code/personal/direkshanProjects/googleAssistant/smarthome-washer/washer-start/functions/node_modules/@firebase/database/dist/index.node.cjs.js:15526:130)
    at FirebaseAppImpl._getService (/Users/prafulll/code/personal/direkshanProjects/googleAssistant/smarthome-washer/washer-start/functions/node_modules/@firebase/app/dist/index.cjs.js:134:66)
    at FirebaseAppImpl.(anonymous function) [as database] (/Users/prafulll/code/personal/direkshanProjects/googleAssistant/smarthome-washer/washer-start/functions/node_modules/@firebase/app/dist/index.cjs.js:323:31)
    at Object.serviceNamespace [as database] (/Users/prafulll/code/personal/direkshanProjects/googleAssistant/smarthome-washer/washer-start/functions/node_modules/@firebase/app/dist/index.cjs.js:308:32)
    at Object.<anonymous> (/Users/prafulll/code/personal/direkshanProjects/googleAssistant/smarthome-washer/washer-start/functions/index.js:28:30)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)

Having trouble? Try firebase deploy --help
```

**Comment by TheDreamSaver** [comment]
Facing the same issue. Please help!

**Comment by Fleker** [comment]
Yeah it looks like a combination of a new major version of `firebase-tools` and some older logic of the functions is resulting in some issues.

In the short-term, you should be able to use an older version of firebase-tools. `npm install firebase-tools@3.19.3` and then run `./node_modules/.bin/firebase deploy`.

I'll look into updating everything on Monday.

**Comment by TheDreamSaver** [comment]
Still getting the same issue @Fleker. See if you can replicate it and help me out with this, please.

**Comment by TheDreamSaver** [comment]
I changed my package.json from -

`{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "engines": {
    "node": ">=6.11.1"
  },
  "dependencies": {
    "actions-on-google": "^2.1.0",
    "cors": "^2.8.4",
    "firebase": "^4.0.0",
    "firebase-admin": "^5.8.1",
    "firebase-functions": "^0.8.1",
    "google-auth-library": "^0.10.0",
    "googleapis": "^27.0.0"
  },
  "private": true,
  "devDependencies": {
    "eslint": "^4.19.1",
    "eslint-config-google": "^0.9.1"
  }
}`

to -

`{
  "name": "functions",
  "description": "Cloud Functions for Firebase",
  "engines": {
    "node": ">=6.11.1"
  },
  "dependencies": {
    "actions-on-google": "2.1.0",
    "cors": "2.8.4",
    "firebase": "4.0.0",
    "firebase-admin": "5.8.1",
    "firebase-functions": "0.8.1",
    "google-auth-library": "0.10.0",
    "googleapis": "27.0.0"
  },
  "private": true,
  "devDependencies": {
    "eslint": "4.19.1",
    "eslint-config-google": "0.9.1"
  }
}`

changed all the  "^2.1.0" to "2.1.0"

**Comment by Fleker** [comment]
That's very interesting, as I wouldn't anticipate that having an issue, but it is good to see you resolved your issue. I will be sure to update the dependencies so it works well out of the box.
